[build]
  base = ""
  publish = "frontend/build"
  functions = "netlify/functions"
  command = "cd frontend && npm install && npm run build"

[dev]
  command = "npm run start"
  targetPort = 3000 # default create-react-app dev server port
  port = 8888       # Netlify Dev port
